const JsonData = [
  {
    shipmentId: 'SH001',
    sender: 'Quantum Computer Services',
    receiver: 'Airi Satou',
    product: 'Laptop',
    quantity: 5,
    carrier: 'DHL',
    status: 'In Transit',
    shipmentDate: '2024-10-05',
    deliveryDate: '2024-10-10',
  },
  {
    shipmentId: 'SH002',
    sender: 'BackRub',
    receiver: 'Claudine Neal',
    product: 'Smartphone',
    quantity: 10,
    carrier: 'FedEx',
    status: 'Delivered',
    shipmentDate: '2024-09-10',
    deliveryDate: '2024-09-15',
  },
  {
    shipmentId: 'SH003',
    sender: 'Best Buy',
    receiver: 'Beryl Rice',
    product: 'Television',
    quantity: 3,
    carrier: 'UPS',
    status: 'Pending',
    shipmentDate: '2024-11-01',
    deliveryDate: '2024-11-05',
  },
  {
    shipmentId: 'SH004',
    sender: 'Apple, Inc.',
    receiver: 'Wilder Gonzales',
    product: 'Smartwatch',
    quantity: 7,
    carrier: 'USPS',
    status: 'Processing',
    shipmentDate: '2024-10-15',
    deliveryDate: '2024-10-20',
  },
  {
    shipmentId: 'SH005',
    sender: 'Blackberry',
    receiver: 'Georgina Schultz',
    product: 'Tablet',
    quantity: 12,
    carrier: 'DHL',
    status: 'Delivered',
    shipmentDate: '2024-09-25',
    deliveryDate: '2024-09-30',
  },
  {
    shipmentId: 'SH006',
    sender: 'Pepsi-Cola',
    receiver: 'Carroll Buchanan',
    product: 'Soft Drink',
    quantity: 100,
    carrier: 'FedEx',
    status: 'Shipped',
    shipmentDate: '2024-10-07',
    deliveryDate: '2024-10-12',
  },
  {
    shipmentId: 'SH007',
    sender: 'Tokyo Tsushin Kogyo',
    receiver: 'Valarie Atkinson',
    product: 'Television',
    quantity: 8,
    carrier: 'UPS',
    status: 'Delivered',
    shipmentDate: '2024-09-17',
    deliveryDate: '2024-09-22',
  },
  {
    shipmentId: 'SH008',
    sender: 'Starbucks',
    receiver: 'Schroeder Mathews',
    product: 'Coffee Machine',
    quantity: 4,
    carrier: 'USPS',
    status: 'Pending',
    shipmentDate: '2024-11-05',
    deliveryDate: '2024-11-10',
  },
  {
    shipmentId: 'SH009',
    sender: 'Nike',
    receiver: 'Lynda Mendoza',
    product: 'Sports Shoes',
    quantity: 25,
    carrier: 'DHL',
    status: 'In Transit',
    shipmentDate: '2024-10-10',
    deliveryDate: '2024-10-15',
  },
  {
    shipmentId: 'SH010',
    sender: 'Hertz Rent-A-Car',
    receiver: 'Sarah Massey',
    product: 'Car Rental Service',
    quantity: 1,
    carrier: 'FedEx',
    status: 'Delivered',
    shipmentDate: '2024-09-05',
    deliveryDate: '2024-09-10',
  },
  // Add more entries as needed...
];

// eslint-disable-next-line import/prefer-default-export
export { JsonData };
