const JsonData = [
  {
    productName: 'Airi Satou',
    category: 'Female',
    brand: 'Quantum Computer Services',
    price: 100,
    quantity: 1,
  },
  {
    productName: 'Claudine Neal',
    category: 'Female',
    brand: 'BackRub',
    price: 200,
    quantity: 2,
  },
  {
    productName: 'Beryl Rice',
    category: 'Female',
    brand: 'Best Buy',
    price: 150,
    quantity: 1,
  },
  {
    productName: 'Wilder Gonzales',
    category: 'Male',
    brand: 'Apple, Inc.',
    price: 300,
    quantity: 1,
  },
  {
    productName: 'Georgina Schultz',
    category: 'Female',
    brand: 'Blackberry',
    price: 250,
    quantity: 1,
  },
  {
    productName: 'Carroll Buchanan',
    category: 'Male',
    brand: 'Pepsi-Cola',
    price: 120,
    quantity: 3,
  },
  {
    productName: 'Valarie Atkinson',
    category: 'Female',
    brand: 'Tokyo Tsushin Kogyo',
    price: 180,
    quantity: 1,
  },
  {
    productName: 'Schroeder Mathews',
    category: 'Male',
    brand: 'Starbucks',
    price: 200,
    quantity: 2,
  },
  {
    productName: 'Lynda Mendoza',
    category: 'Female',
    brand: 'Nike',
    price: 220,
    quantity: 1,
  },
  {
    productName: 'Sarah Massey',
    category: 'Female',
    brand: 'Hertz Rent-A-Car',
    price: 130,
    quantity: 1,
  },
  {
    productName: 'Robles Boyle',
    category: 'Male',
    brand: 'eBay',
    price: 140,
    quantity: 1,
  },
  {
    productName: 'Evans Hickman',
    category: 'Male',
    brand: 'International Business Machines',
    price: 250,
    quantity: 1,
  },
  {
    productName: 'Dawson Barber',
    category: 'Male',
    brand: 'Nintendo',
    price: 220,
    quantity: 1,
  },
  {
    productName: 'Bruce Strong',
    category: 'Male',
    brand: 'SUBWAY',
    price: 160,
    quantity: 1,
  },
  {
    productName: 'Nellie Whitfield',
    category: 'Female',
    brand: 'Circuit City',
    price: 140,
    quantity: 2,
  },
  {
    productName: 'Jackson Macias',
    category: 'Male',
    brand: 'Firefox',
    price: 180,
    quantity: 1,
  },
  {
    productName: 'Pena Pena',
    category: 'Male',
    brand: 'PayPal',
    price: 210,
    quantity: 1,
  },
  {
    productName: 'Lelia Gates',
    category: 'Female',
    brand: 'Yahoo',
    price: 220,
    quantity: 1,
  },
  {
    productName: 'Letitia Vasquez',
    category: 'Female',
    brand: 'Wrappixel',
    price: 180,
    quantity: 2,
  },
  {
    productName: 'Trevino Moreno',
    category: 'Male',
    brand: 'Blackbuck',
    price: 150,
    quantity: 1,
  },
  {
    productName: 'Barr Page',
    category: 'Male',
    brand: 'Apex',
    price: 130,
    quantity: 1,
  },
  {
    productName: 'Kirkland Merrill',
    category: 'Male',
    brand: 'Nokia',
    price: 200,
    quantity: 1,
  },
  {
    productName: 'Blanche Conley',
    category: 'Female',
    brand: 'Reliance Industries',
    price: 170,
    quantity: 1,
  },
];

export { JsonData };
